# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0002_auto_20170726_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='code',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
