# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0003_auto_20170726_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='length',
        ),
    ]
