# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0004_remove_session_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='length',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
